### PR TITLE
Update secured_service_with_jwt.client.out

### PR DESCRIPTION
**Pull request by sherenem**
## Purpose
TCC review: minor fix

### CODE REVIEW

**Review by pubudu91 — COMMENTED** [review]
In lines 1 and 3, curl -> cURL

**Comment by sherenewso2** [comment]
@pubudu91 Fixed with commit https://github.com/ballerina-platform/ballerina-examples/pull/761/commits/6a4d9251c3005feb7aa2e07db3a8aa693be42d2f

**Review by pubudu91 — APPROVED** [review]

**Comment by pubudu91** [comment]
@sherenewso2 Can you please resolve the conflict as well?

**Comment by sherenewso2** [comment]
@pubudu91 done.

**Pull request merged**
